Update main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -21,61 +21,61 @@ num_epochs=`jq -r '.num_epochs' config.json`
 if [ ! $num_epochs == null ]; then
 	echo "STARTING TRAINING..."
 
-	python brainlife-utils/create_training_dataset.py
-	SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 brainlife-utils/create_training_dataset.py
-	singularity exec --nv docker://paoloavesani/docker-test \
-                    bin/peaks_to_cnn \
-                    -json brainlife-utils/brainlife_config_training.json
+	#python brainlife-utils/create_training_dataset.py
+	#SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 brainlife-utils/create_training_dataset.py
+	#singularity exec --nv docker://paoloavesani/docker-test \
+        #            bin/peaks_to_cnn \
+        #            -json brainlife-utils/brainlife_config_training.json
                     
-	if [ -d 'final_output/' ]; then 
- 		rm -r final_output
-	fi
+	#if [ -d 'final_output/' ]; then 
+ 	#	rm -r final_output
+	#fi
 	
-	if [ -d 'weights/' ]; then 
- 		rm -r weights
-	fi
+	#if [ -d 'weights/' ]; then 
+ 	#	rm -r weights
+	#fi
 
-	mv output final_output
-	mkdir weights
-	mv final_output/*.npz weights/.
- 	mv final_output/Hyperparameters.txt weights/.
-	mkdir images
-	mv final_output/*.png images/.
-	cp brainlife-utils/brainlife_config_training.json images.json
-
-	if [ -f weights/*.npz ]; then 
-		echo "Training completed."
-	else 
-		echo "Weights missing."
-		exit 1
-	fi
+	#mv output final_output
+	#mkdir weights
+	#mv final_output/*.npz weights/.
+ 	#mv final_output/Hyperparameters.txt weights/.
+	#mkdir images
+	#mv final_output/*.png images/.
+	#cp brainlife-utils/brainlife_config_training.json images.json
+	mv weights/*.npz weights/weights.npz
+	#if [ -f weights/*.npz ]; then 
+	#	echo "Training completed."
+	#else 
+	#	echo "Weights missing."
+	#	exit 1
+	#fi
   
 else
 	echo "STARTING TEST..."
 
-	#if [ -d 'test_output/' ]; then 
- 	#	rm -r test_output
-	#fi
+	if [ -d 'test_output/' ]; then 
+ 		rm -r test_output
+	fi
 
   	#CMD="brainlife-utils/create_test_dataset.py && \
   	#bin/peaks_to_cnn -json brainlife-utils/brainlife_config_test.json && \
   	#brainlife-utils/adjust_test_output.py"
 	#SINGULARITYENV_PYTHONNOUSERSITE=true
-	#singularity exec -e --nv docker://paoloavesani/docker-test bash -c "brainlife-utils/create_test_dataset.py && \
-  	#bin/peaks_to_cnn -json brainlife-utils/brainlife_config_test.json && \
-  	#brainlife-utils/adjust_test_output.py"
+	singularity exec -e --nv docker://paoloavesani/docker-test bash -c "brainlife-utils/create_test_dataset.py && \
+  	bin/peaks_to_cnn -json brainlife-utils/brainlife_config_test.json && \
+  	brainlife-utils/adjust_test_output.py"
 
-  	#if [ -d 'tractseg_output/' ]; then 
- 	#	rm -r tractseg_output
-	#fi
-	#mkdir tractseg_output
-  	#mv test_output tractseg_output
-   	mv weights/*.npz weights/weights.npz
-	#if [ -z "$(ls -A -- "tractseg_output")" ]; then    
-	#	echo "tractseg_output is empty."; 
-	#	exit 1;
-	#else    
-	#	echo "test done." 
-	#fi
+  	if [ -d 'tractseg_output/' ]; then 
+ 		rm -r tractseg_output
+	fi
+	mkdir tractseg_output
+  	mv test_output tractseg_output
+   	
+	if [ -z "$(ls -A -- "tractseg_output")" ]; then    
+		echo "tractseg_output is empty."; 
+		exit 1;
+	else    
+		echo "test done." 
+	fi
 fi   
 
