Update main

diff --git a/main b/main
--- a/main
+++ b/main
@@ -14,41 +14,41 @@ set -x
 
 num_epochs=`jq -r '.num_epochs' config.json`
 
-#if [ -d 'dataset/' ]; then 
-#	rm -r dataset
-#fi
+if [ -d 'dataset/' ]; then 
+	rm -r dataset
+fi
 
 if [ ! $num_epochs == null ]; then
 	echo "STARTING TRAINING..."
 
-	#python brainlife-utils/create_training_dataset.py
-	#SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 brainlife-utils/create_training_dataset.py
-	#singularity exec --nv docker://paoloavesani/docker-test \
-        #            bin/peaks_to_cnn \
-        #            -json brainlife-utils/brainlife_config_training.json
+	python brainlife-utils/create_training_dataset.py
+	SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/dipy:0.16.0 brainlife-utils/create_training_dataset.py
+	singularity exec --nv docker://paoloavesani/docker-test \
+                    bin/peaks_to_cnn \
+                    -json brainlife-utils/brainlife_config_training.json
                     
-	#if [ -d 'final_output/' ]; then 
- 	#	rm -r final_output
-	#fi
+	if [ -d 'final_output/' ]; then 
+ 		rm -r final_output
+	fi
 	
-	#if [ -d 'weights/' ]; then 
- 	#	rm -r weights
-	#fi
+	if [ -d 'weights/' ]; then 
+ 		rm -r weights
+	fi
 
-	#mv output final_output
-	#mkdir weights
-	#mv final_output/*.npz weights/.
- 	#mv final_output/Hyperparameters.txt weights/.
-	#mkdir images
-	#mv final_output/*.png images/.
-	#cp brainlife-utils/brainlife_config_training.json images.json
-	mv weights/*.npz weights/weights.npz
-	#if [ -f weights/*.npz ]; then 
-	#	echo "Training completed."
-	#else 
-	#	echo "Weights missing."
-	#	exit 1
-	#fi
+	mv output final_output
+	mkdir weights
+	mv final_output/*.npz weights/weights.npz
+ 	mv final_output/Hyperparameters.txt weights/Hyperparameters.txt
+	mkdir images
+	mv final_output/*.png images/.
+	cp brainlife-utils/brainlife_config_training.json images.json
+	
+	if [ -f weights/*.npz ]; then 
+		echo "Training completed."
+	else 
+		echo "Weights missing."
+		exit 1
+	fi
   
 else
 	echo "STARTING TEST..."
@@ -63,7 +63,7 @@ else
 	#SINGULARITYENV_PYTHONNOUSERSITE=true
 	singularity exec -e --nv docker://paoloavesani/docker-test bash -c "brainlife-utils/create_test_dataset.py && \
   	bin/peaks_to_cnn -json brainlife-utils/brainlife_config_test.json && \
-  	brainlife-utils/adjust_test_output.py"
+  	brainlife-utils/adjust_test_output.py && create_wmc.py"
 
   	if [ -d 'tractseg_output/' ]; then 
  		rm -r tractseg_output
